[package]
name = "adventofcode2017"
version = "0.1.0"
authors = ["Ludwig PACIFICI <ludwig@lud.cc>"]

[dependencies]
bytecount = "*"
failure = "*"
itertools = "*"
lazy_static = "*"
primal = "*"
regex = "*"
